version: '3'
services:
  rapimo:
    build:
      context: .
      dockerfile: Dockerfile.rapimo
    container_name: rapimo
    ports:
      - "127.0.0.1:48000:8000"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx
    ports:
      - "40080:80"
      - "40443:443"
    volumes:
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - rapimo
